# Generated by Django 4.0.4 on 2022-04-28 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='nome_endereco',
        ),
    ]
