# Generated by Django 4.0.4 on 2022-05-05 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0004_alter_perfil_primeiro_nome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='primeiro_nome',
            field=models.CharField(max_length=100, verbose_name='Nome'),
        ),
    ]
